-- 데이터가 없는 시간대에도 count가 0으로 조회되어야 한다.
WITH RECURSIVE TIME AS(
SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1 FROM TIME WHERE HOUR < 23)
SELECT HOUR, COUNT(HOUR(DATETIME)) AS 'COUNT'
FROM TIME LEFT OUTER JOIN ANIMAL_OUTS
ON (HOUR=HOUR(DATETIME))
GROUP BY HOUR