-- 코드를 입력하세요
-- 결과는 나오는데 오답..
SELECT SUBSTRING(DATETIME,12,2) HOUR, COUNT(*) COUNT
FROM ANIMAL_OUTS
WHERE SUBSTRING(DATETIME,12,2) >= 9
GROUP BY SUBSTRING(DATETIME,12,2)
ORDER BY SUBSTRING(DATETIME,12,2) ASC;

-- 풀이 1
SELECT HOUR(DATETIME) AS HOUR, COUNT(*) COUNT
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME)>= 9 AND HOUR(DATETIME)<20
GROUP BY HOUR(DATETIME)
ORDER BY HOUR(DATETIME) ASC;

-- 풀이 2
SELECT HOUR(DATETIME) AS HOUR, COUNT(*) COUNT
FROM ANIMAL_OUTS
GROUP BY HOUR(DATETIME)
HAVING HOUR BETWEEN 9 AND 19
ORDER BY HOUR(DATETIME) ASC;
