# AI 보호일보다 AO 입양일이 빠르게 입력된 데이터 조회
# 보호시작일 빠른 순 조회
-- 코드를 입력하세요
SELECT AO.ANIMAL_ID, AO.NAME
FROM ANIMAL_OUTS AO
LEFT JOIN ANIMAL_INS AI
ON AI.ANIMAL_ID=AO.ANIMAL_ID
WHERE AI.DATETIME > AO.DATETIME
ORDER BY AI.DATETIME ASC; 