-- 풀이 1
SELECT AO.ANIMAL_ID, AO.NAME
FROM ANIMAL_OUTS AO
WHERE AO.ANIMAL_ID NOT IN (
    SELECT AI.ANIMAL_ID
    FROM ANIMAL_INS AI
)
ORDER BY AO.ANIMAL_ID;
-- 풀이 2
SELECT AO.ANIMAL_ID, AO.NAME
FROM ANIMAL_OUTS AO
LEFT JOIN ANIMAL_INS AI
ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE AI.ANIMAL_ID IS NULL
ORDER BY AO.ANIMAL_ID;